import { useCallback, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { SaitamaInputForm } from '../components/SaitamaInputForm';

export default function Home() {
  const [isSaitama, setIsSaitama] = useState<boolean | undefined>(undefined);
  const handle = useCallback((bool: boolean) => {
    setIsSaitama(bool);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Saitama.js vol.4 「再実装 React Testing Library」</h1>
        <SaitamaInputForm handle={handle} />
        {isSaitama === undefined
          ? null
          : isSaitama
          ? 'LGTM'
          : 'いつか埼玉に遊びにきてね'}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
